language: node_js
node_js:
 - "node"
after_success:
 - git config --local user.name "Prafull Kotecha"
 - git config --local user.email "prafull.kotecha@gmail.com"
 - git remote rm origin
 - git remote add origin https://prafullkotecha:zkAwy29DpZa3CQibSsFN@github.com/direkshan-digital/save-favorite-bookmarks.git
 - npm run deploy
